import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import { Poppins } from "next/font/google";
import Footer from "./components/footer";

const poppins = Poppins({
  subsets: ["latin"],     // choose character set
  weight: ["400", "600"], // choose weights
  variable: "--font-poppins", // CSS variable for Tailwind
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"  className={`${poppins.variable}`}>
     <body
  className={`${geistSans.variable} ${geistMono.variable} antialiased`}
  cz-shortcut-listen="true"   // dono side consistent
>
<div className="relative z-50" >
  <Header/>
</div>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
